name: push actions
on: [push]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12', '3.13']
        poetry-version: [2.1]
        os: [ubuntu-24.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v3.0.2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: poetry install
        run: poetry install
      - name: mypy
        run: poetry run mypy simple_html
      - name: run tests
        run: poetry run pytest
      - name: run bench (pure python)
        run: poetry run python -m bench.run

